### ISSUE TITLE
The OpenGL backend is not available on MacOS

### ISSUE THREAD

**Issue by GabrielRavier** [Clownacy/Cave-Story-Engine-2#100]
As https://github.com/Clownacy/Cave-Story-Engine-2/blob/0902b9e35d438418afb39e9fe41f365655fa4e17/.travis.yml#L62-L66 documents, Apple's OpenGL implementation is very badly made. Still, it would be nice to have support for it in the future

**Comment by Clownacy** [comment]
As of d7ca8b3874ba13acc2ab50954e55fcb5a4744f54, this is no longer an issue.
