### ISSUE TITLE
CMake builds never fail on Travis-CI

### ISSUE THREAD

**Issue by GabrielRavier** [Clownacy/Cave-Story-Engine-2#103]
No matter what happens during the CMake build, Travis-CI seems to completely ignore it and go on without considering any problem occured

See for example [this build](https://travis-ci.com/Clownacy/Cave-Story-Engine-2/jobs/286976693) that obviously should have failed but was marked as a success

**Comment by Clownacy** [comment]
I'm not too sure about how Travis determines build-failure, but the way it describes the build succeeding makes me think it resolves entire blocks of commands at a time. In that case, the problem might be it's only checking the exit code of the `cd ..` command, and not the `cmake` invocation:
```
The command "if [ "$BUILD_SYSTEM" == "cmake" ]; then
  # CMake build
  cd ${CMAKE_BUILD_DIR}
  cmake --build . --config Release --parallel $JOBS
  cd ..
else
  # Make build
  make -j $JOBS FIX_BUGS=1 RELEASE=1 WARNINGS=1 WARNINGS_ALL=1 RENDERER=$RENDERER
fi
" exited with 0.
```

**Comment by AJenbo** [comment]
Yeah you need to make each depend on the state of the previous with &&

**Comment by Clownacy** [comment]
This scripting no longer exists in an `if` as of d7ca8b3874ba13acc2ab50954e55fcb5a4744f54, so this should no longer be an issue.

**Comment by AJenbo** [comment]
looks good
