### ISSUE TITLE
<MIM does not persist in save files

### ISSUE THREAD

**Issue by Aarmaster11** [Clownacy/Cave-Story-Engine-2#104]
When using <MIM in the enhanced branch and saving, the character reverts to <MIM0000 upon re-loading.

**Comment by GabrielRavier** [comment]
Looked at it a little and it seems to be caused by `gMIMCurrentNum` not being saved to the profile. In the original hack, I believe it is stored within the flags, so it gets saved, but in CSE2 it's stored seperately

**Comment by Clownacy** [comment]
Should <PHY be persistent as well?

**Comment by GabrielRavier** [comment]
I believe <PHY values were stored there too, yeah

**Comment by Clownacy** [comment]
I just realised: to fix this, we'd have to change the Profile.dat format. Either we'd have to add data to the end, or shrink the flags, and fix the new data in the gap.

**Comment by Aarmaster11** [comment]
I planned on doing a couple cool save-compatibility things with the mod I'm working on, but it's definitely not a necessity.

**Comment by Clownacy** [comment]
Alternatively, extra data could go in a new file, like 'ProfileExtra.dat'. If the extra file is not found, its values are set to sane default values, and the game continues as normal, maintaining backwards-compatibility.

**Comment by Clownacy** [comment]
Does the new commit fix this problem?

**Comment by Aarmaster11** [comment]
Yes, it does. Thank you!
