### ISSUE TITLE
[Portable/Enhanced] Weird static/hissing at the start of Gestation

### ISSUE THREAD

**Issue by Leo40Git** [Clownacy/Cave-Story-Engine-2#108]
**[DEAD LINK]**
That... doesn't sound right.

**Comment by Clownacy** [comment]
It sounds normal to me. What am I supposed to be listening for?

**Comment by Leo40Git** [comment]
So... you don't hear the hissing or whatever? Maybe my headphones are more damaged than I thought...
Regardless, I forgot to mute my mic and my dumb breathing's in the way. I'll get a cleaner recording.

**Comment by Leo40Git** [comment]
NVM, happens with SDL2 backend too, my headphones are kinda fucked.

**Comment by Leo40Git** [comment]
...the hissing doesn't happen in the original game, apparently? Lemme try to build the "accurate" branch real quick.

**Comment by Leo40Git** [comment]
Does not happen on "accurate" branch.

**Comment by GabrielRavier** [comment]
Most likely, your headphones change what is a very slight inaccuracy into the horrible screeching that you seem to hear. Maybe we could try to peek into the exact sound output to see the difference with what the original game plays ? I'd assume it's not out of the realm of possibility that DirectSound does some slight transformation on the sound.

**Comment by Clownacy** [comment]
I can only imagine it's a resampling thing: CSE2's software mixer uses a plain linear resampler, whereas the accurate branch offloads mixing onto DirectSound, so it uses whatever that uses.

**Comment by Leo40Git** [comment]
Apparently recording it doesn't work, but just in case, here's a clean recording:
https://www.dropbox.com/s/adsc32fj63k43wv/CSE2%20Portable%20Buzz.mkv?dl=0

**Comment by Leo40Git** [comment]
THE BEES ARE DEAD AND bcd883e767526e7e5f4a8fae0c68853ee8ea1e00 KILLED THEM
