### ISSUE TITLE
A few crashes with text in the Enhanced branch

### ISSUE THREAD

**Issue by AllyTally** [Clownacy/Cave-Story-Engine-2#116]
Other than [the font being incorrect](https://o.lol-sa.me/2YDGizS.png), I've found a few crashes when the game tries to display text in a few places (possibly to do with the incorrect font? unsure).
The first one happens on line 1604 in `cute_spritebatch.h` with `SPRITEBATCH_ASSERT(!(max_x < 0));`, where the error happened during the `Sue! Answer me!` cutscene.
The second crash is inconsistent, though it happened once while checking Arthur's grave, if that's any useful information. The crash was on line 1560 of `SDL_render.c`.

I'm on Visual Studio 2019 Version 16.1.5, MSVC 19.21.27702.2 on Windows 10 build 1809.

**Comment by Clownacy** [comment]
The font isn't incorrect - it just isn't Courier New. From what I can tell, Courier New is proprietary, so I can't distribute it with this project (and I'd rather not add platform-dependant system font loading).

Instead, I settled on a font that's compatible with CSE2's font renderer (some fonts just don't render correctly, for some reason), is under a suitable licence, has decent internationalisation support, and looks reasonably-good at 320x240.

I've been getting sparse reports of that `SPRITEBATCH_ASSERT` error for a while, but having a proper build environment description should help track it down. Thanks.

**Comment by AllyTally** [comment]
[Here's](https://o.lol-sa.me/5g7ybdL.mp4) a video of the second crash. I'm unsure how useful this is due to it happening seemingly randomly, though

**Comment by Clownacy** [comment]
The spritebatch issue should be fixed, and I couldn't recreate the other crash.

**Comment by AllyTally** [comment]
It seems like the second crash was happening due to my bad bandaid fix for the first issue, whoops
Thanks!
