### ISSUE TITLE
How to load Ogg soundtrack files?

### ISSUE THREAD

**Issue by Nilot352** [Clownacy/Cave-Story-Engine-2#119]
I am trying to use this mod [here](https://www.cavestory.org/forums/threads/cave-story-arranged.5837/), but I have no idea where to place the files.

**Comment by BombchuLink** [comment]
You'll need to change the music table at Stage.cpp:311
Change the file names from .org to .ogg and the music type from MUSIC_TYPE_ORGANYA to MUSIC_TYPE_OTHER
Also make sure you have 2 lines for each song if its the remastered soundtrack (_intro, _loop)

As an example replace...
```
{"Resource/ORG/XXXX.org", MUSIC_TYPE_ORGANYA, true},
```
with
```
{"Resource/ORG/XXXX_intro.ogg", MUSIC_TYPE_OTHER, true},
{"Resource/ORG/XXXX_loop.ogg", MUSIC_TYPE_OTHER, true},
```

**Comment by Clownacy** [comment]
That's not correct: if the song is split, both files should go on the same line:
```c
{"Soundtracks/Famitracks/wanpaku_intro.ogg", "Soundtracks/Famitracks/wanpaku_loop.ogg", MUSIC_TYPE_OTHER, true},
```
Cave Story Arranged doesn't use split files anyway, so this isn't necessary.

**Comment by Clownacy** [comment]
If there's a problem, feel free to reopen this issue.
