### ISSUE TITLE
that aint quote

### ISSUE THREAD

**Issue by Awesomegamer6566** [Clownacy/Cave-Story-Engine-2#120]
![image](https://user-images.githubusercontent.com/50709579/81371249-3408fb80-90ac-11ea-8320-4e61c273d5c8.png)
thats sonic

**Comment by Riteo** [comment]
Oh god oh fuck

**Comment by Clownacy** [comment]
The Emscripten port is no longer maintained. Also, I can't control what icon that website uses - I don't own it.
