### ISSUE TITLE
Most of the original source files appear to be C89

### ISSUE THREAD

**Issue by Clownacy** [Clownacy/Cave-Story-Engine-2#41]
Files converted to C89 so far:
* Star.cpp
* ValueView.cpp

Files that don't seem to be C89:
* Input.cpp (COM object accesses produce different assembly code in C)
* Triangle.cpp (sin and cos calls produce different assembly in C)

====================================

The original EXE's Rich Header details that most of the object files used to create the EXE were created by a C compiler, not C++.

The biggest problem with making the switch is that MSVC2003 only supported C89/C90, so all the code needs changing so that variable declarations come before the actual code.

The debug data left in the Linux port actually specifies the exact line number each variable was defined on. If the original game's code really was C89, then they should always be clumped together. I haven't checked this though.

The Rich Header _did_ still count a few C++ files. These were likely the DirectX-related files (Draw.cpp, Organya.cpp, etc.) and possibly C++-based libraries linked into the EXE.

Admittedly, the Linux debug data also provides filenames, and they all end in '.cpp'. I think this might have been one of the Linux port's modifications, however.

**Comment by Clownacy** [comment]
Interestingly, [Triangle.cpp uses `sin` and `cos`](https://github.com/Clownacy/Cave-Story-Engine-2/commit/7f7553bef25fa9f0f5a0f69b3d7a58527cc3ee97) in a way [that Microsoft claims is C++-only](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/sin-sinf-sinl?view=vs-2019).

**Comment by GabrielRavier** [comment]
Does that still generate accurate code ? MSVC in C mode could simply be supporting tgmath, no ?

**Comment by Clownacy** [comment]
I just get a 'include file not found' error if I try to include tgmath in C mode.

**Comment by GabrielRavier** [comment]
Does this change still generate accurate code though ? Also, does this mean that InitTriangleTable is compiled as C++ or ?

**Comment by Clownacy** [comment]
I said in the commit message that the change doesn't affect ASM.

**Comment by Clownacy** [comment]
As a quick test, I converted Star.cpp to C89, and checked the resulting EXE's Rich Header:
```
@comp.id   id version count   description
00690813   69   2067     1
000f0c05    f   3077    26    obj files produced by assembler
005d0813   5d   2067     2
001d23da   1d   9178     1
005d0883   5d   2179    10
001c23da   1c   9178     1
001923fa   19   9210    11
00010000    1      0   158
005f0c05   5f   3077   128    obj files produced by C compiler
00600c05   60   3077    70    obj files produced by C++ compiler
005e0bec   5e   3052     1    obj files produced by CVTRES converter
005a0c05   5a   3077     1
```

As you can see, the 'obj files produced by C compiler' value was incremented, and the 'obj files produced by C++ compiler' was decremented.

This is strange, because now the C-compiler value is _higher_ than the vanilla EXE, whereas previously they were the same.

**Comment by Clownacy** [comment]
If link-time optimisation is enabled in VS2003, then the number of C++ object goes down to 2, the number of C objects does down to 127, and a new value with an ID of 64 appears, totalling the number of source files. Notably, the vanilla EXE has a similar number, attributed to ID 62 instead. It seems like the original EXE was built with a different configuration that the default. The question is, which one? What is ID 62?

**Comment by Clownacy** [comment]
Okay, [this blog post](http://ropgadget.com/posts/richheader_hunting.html) has a list of references on decoding various IDs - [this one in particular](https://gist.github.com/skochinsky/07c8e95e33d9429d81a75622b5d24c8b) is interesting because it's apparently based on a leak, and thoroughly covers a huge range of IDs, which matches up with current info.

These are the values relevant to VS2003:
```
  90: "Linker710",
  91: "Cvtomf710",
  92: "Export710",
  93: "Implib710",
  94: "Cvtres710",
  95: "Utc1310_C",
  96: "Utc1310_CPP",
  97: "Utc1310_C_Std",
  98: "Utc1310_CPP_Std",
  99: "Utc1310_LTCG_C",
  100: "Utc1310_LTCG_CPP",
  101: "Utc1310_POGO_I_C",
  102: "Utc1310_POGO_I_CPP",
  103: "Utc1310_POGO_O_C",
  104: "Utc1310_POGO_O_CPP",
```
Indeed, 95 (0x5F) is the C compiler, 96 (0x60) is the C++ compiler, and 100 (0x64) is the LTO C++ compiler. According to this, 100 (0x62) is "Utc1310_CPP_Std".

...Well okay, assuming this is accurate, then Cave Story really was written in C++ and I'm a giant dumbass, but the important question is what the hell "Utc1310_CPP_Std" means. The C++ compiler except it's more standard?

If it means 'standards-conformant', then I'm not sure what _that_ means, since compiling a quick test program with extensions disabled just gives me a Rich Header with ID 60 again.

**Comment by Clownacy** [comment]
Now that I think about it, 'standard' might refer to Visual Studio .NET 2003's Standard edition. I have the Professional edition, but maybe the standard one uses a nerfed compiler?

...Not a chance anyone still has a copy of that to check?

**Comment by Clownacy** [comment]
> The debug data left in the Linux port actually specifies the exact line number each variable was defined on. If the original game's code really was C89, then they should always be clumped together. I haven't checked this though.

After finally getting around to this, and combined with the above info, I think it's safe to say Cave Story wasn't written in C89 - it's just C++ that _looks like_ C89. Notably, there are many functions that mix code and declarations in a way C89 would never allow.
