### ISSUE TITLE
Detection of FLTK system library requires fltk-fluid

### ISSUE THREAD

**Issue by GabrielRavier** [Clownacy/Cave-Story-Engine-2#45]
fltk-fluid is a program used for creating C++ code using FLTK (It's a UI designer like the one in Qt Creator). This is not required to build CSE2, and isn't built with the builtin libraries. Therefore, I recommend we update the detection code in CMakeLists.txt to not require fltk-fluid (the CMake detection script lets you know if fltk-fluid was found, so I'm pretty sure this is possible without manually detecting fltk ourselves)

**Comment by Clownacy** [comment]
Should be fixed now, but could use testing.

**Comment by GabrielRavier** [comment]
Can confirm it now works
