### ISSUE TITLE
System SDL2-static is not detected

### ISSUE THREAD

**Issue by GabrielRavier** [Clownacy/Cave-Story-Engine-2#46]
The CMake build files will always build a static version of SDL2, even when a static version of SDL2 is already present on the system. Therefore, I recommend that some detection code be added to CMakeLists.txt be updated to detect the presence of such a library (for example, SDL2-static in Fedora) and use it if available.

**Comment by Clownacy** [comment]
Should be fixed now, but could use testing.

**Comment by GabrielRavier** [comment]
Seems like it doesn't work, just tested on my Fedora 30 laptop with SDL2-static installed and it still builds SDL2

**Comment by Clownacy** [comment]
Can you send me your SDL2Targets.cmake file then? SDL2 can't seem to decide how to declare itself. Just look at this nonsense:
```
if(TARGET SDL2::SDL2)
	# CMake-generated config (Arch, vcpkg, Raspbian)
	message(STATUS "Using system SDL2")
	target_link_libraries(CSE2 SDL2::SDL2 SDL2::SDL2main)
elseif(TARGET SDL2::SDL2-static)
	# CMake-generated config (Arch, vcpkg, Raspbian)
	message(STATUS "Using system SDL2")
	target_link_libraries(CSE2 SDL2::SDL2-static SDL2::SDL2main)
elseif(SDL2_FOUND)
	# Autotools-generated config (MSYS2)
	message(STATUS "Using system SDL2")
	target_include_directories(CSE2 PRIVATE ${SDL2_INCLUDE_DIRS})
	target_link_libraries(CSE2 ${SDL2_LIBRARIES})
```

**Comment by GabrielRavier** [comment]
And where would I find that ? It is not present anywhere in /usr

**Comment by Clownacy** [comment]
Maybe your distro is using the autotool-generated one... it should be in /usr/lib/cmake/SDL2, and called 'sdl2-config.cmake'.

**Comment by GabrielRavier** [comment]
$ ll /usr/lib/cmake/SDL2
ls: cannot access '/usr/lib/cmake/SDL2': No such file or directory

**Comment by Clownacy** [comment]
[CMake's find_package searches a bunch of directories](https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure). You'll have to look through them.

**Comment by GabrielRavier** [comment]
`$ find /usr -name "*SDL*.cmake"` found 
`
/usr/share/cmake/Modules/FindSDL.cmake
/usr/share/cmake/Modules/FindSDL_sound.cmake
/usr/share/cmake/Modules/FindSDL_net.cmake
/usr/share/cmake/Modules/FindSDL_ttf.cmake
/usr/share/cmake/Modules/FindSDL_mixer.cmake
/usr/share/cmake/Modules/FindSDL_image.cmake
`, idk where else to search tbh

**Comment by GabrielRavier** [comment]
I searched my entire computer for "*SDL*.cmake" and "SDL*.cmake" and didn't find anything, apart from the files in /usr/share/cmake (for SDL 1.2) and the ones in this repo

**Comment by Clownacy** [comment]
If your distro isn't making SDL2 visible to CMake, then I'm not sure what I can do.

**Comment by Clownacy** [comment]
This is probably no longer an issue, ever since I added `pkg-config` support to the CMake script in ca5b0928075a22693d6bf07e7a5dbab41e3ca286.

**Comment by GabrielRavier** [comment]
Yup, it's indeed no longer an issue
