### ISSUE TITLE
Fullscreen does not work properly

### ISSUE THREAD

**Issue by GabrielRavier** [Clownacy/Cave-Story-Engine-2#47]
On the portable branch, on Linux (at the very least) using fullscreen (with the default config generated by the game when no Config.dat is found) does not work. On my Fedora 30 64-bit machine using Xfce 4.14, this resulted in 30 seconds of the screen alternating between a 640*480 (I think) resolution and the resolution I was at before, before the screen settled on the low resolution. Afterwards, the window containing the game did not properly obtain exclusive fullscreen (as the top Xfce bar was still visible). Instead, a window of the game situated in the rest of the screen not occupied by the Xfce bar was visible. This window did not render anything, instead rendering the window that was behind it in the window order (in my case, my terminal where I had been previously building the game), with the only part showing that the game had indeed created a window being the top bar of the window with the title of the game (Cave Story ~ Doukutsu Monatagari). In my case, my computer was afterwards frozen and I was unable to do anything but restart it after waiting and trying to take any action that would make my computer react for ~20 minutes. 

Image : 
![FrozenDoukutsu.jpg](https://user-images.githubusercontent.com/31440290/64608109-3e161580-d3ca-11e9-9b91-991e99565025.JPG)

The screen was indeed at a low resolution, the photo only looks high res because it was taken very close to the computer.

**Comment by Clownacy** [comment]
Can't replicate this on my system with any of the rendering backends.

**Comment by GabrielRavier** [comment]
I figured this would be the case. What config did you test it on ? (I was using the default SDL2 texture rendering backend btw)

**Comment by Clownacy** [comment]
I tested all backends, and with/without a Config.dat file.

**Comment by GabrielRavier** [comment]
Yeah, but what computer were you using ? This could be an issue with X11, Xfce or Linux. I personally am able to reproduce this consistently on my Fedora 30 64-bit Xfce laptop, though I'd rather not do it often since it crashes my computer

**Comment by Clownacy** [comment]
Arch Linux with Xfce and X11. My GPU driver is amdgpu.

**Comment by GabrielRavier** [comment]
Forgot to mention, I configured the CMake build with -DFIX_BUGS=ON -DDEBUG_SAVE=ON

**Comment by Clownacy** [comment]
That didn't seem to change anything.

**Comment by GabrielRavier** [comment]
For some reason it works now, so I'll leave it at that and close this. (If anybody else encounters this issue, feel free to re-open this issue)
