### ISSUE TITLE
The portable branch segfaults when transitioning from the intro to the title screen

### ISSUE THREAD

**Issue by GabrielRavier** [Clownacy/Cave-Story-Engine-2#48]
See title.

Gonna try to investigate this further and maybe fix it when I have some time, but this seems like a pretty big problem that should probably be fixed ASAP.

Didn't test on anything else than Fedora 30 64-bit btw, so maybe this is OS-dependant ? Used SDL2 texture config for the rendering btw

**Comment by Clownacy** [comment]
Cannot replicate this one either.

**Comment by GabrielRavier** [comment]
I'd personally encourage you to attempt using -DFIX_BUGS=ON -DDEBUG_SAVE=ON for testing this bug too, considering I can consistently getting after directly cloning the repo and config->building->running CSE2

**Comment by Clownacy** [comment]
No difference here.

**Comment by GabrielRavier** [comment]
Just checked with a debug build, the crash occurs [here](https://github.com/Clownacy/Cave-Story-Engine-2/blob/aede7b6069cc6b7502d2f73f8969034df40206bc/src/Organya.cpp#L571) with j=1. Gonna investigate further.

**Comment by GabrielRavier** [comment]
Gonna try regenerating my resource files and see if that helps

**Comment by GabrielRavier** [comment]
Did you try deleting the src/Resource folder and trying to see if the bug occurs ? Just did and it still happens to me

**Comment by Clownacy** [comment]
I remember running into a crash in that same place before. It had to do with Wave.dat not loading.

**Comment by Clownacy** [comment]
Deleting src/Resource did nothing.

**Comment by GabrielRavier** [comment]
Printing info at the faulting point gives this : `$14 = {wait = 92, line = 4 '\004', dot = 6 '\006', alloc_note = 0, repeat_x = 96, end_x = 1464, tdata = {{freq = 1000,
      wave_no = 1 '\001', pipi = 0 '\000', note_p = 0x0, note_list = 0x0}, {freq = 1000, wave_no = 66 'B', pipi = 0 '\000',
      note_p = 0x0, note_list = 0x0}, {freq = 1000, wave_no = 92 '\\', pipi = 0 '\000',	note_p = 0x0, note_list = 0x0}, {freq = 1000,
      wave_no = 63 '?',	pipi = 0 '\000', note_p = 0x0, note_list = 0x0}, {freq = 1000, wave_no = 47 '/', pipi = 0 '\000', 
      note_p = 0x0, note_list = 0x0}, {freq = 1000, wave_no = 47 '/', pipi = 0 '\000', note_p = 0x0, note_list = 0x0}, {freq = 1000,
      wave_no = 63 '?',	pipi = 0 '\000', note_p = 0x0, note_list = 0x0}, {freq = 900, wave_no = 7 '\a',	pipi = 0 '\000', 
      note_p = 0x0, note_list = 0x0}, {freq = 1000, wave_no = 0 '\000',	pipi = 0 '\000', note_p = 0x0, note_list = 0x0}, {
      freq = 1000, wave_no = 2 '\002', pipi = 0 '\000',	note_p = 0x0, note_list = 0x0}, {freq = 1000, wave_no = 5 '\005',
`

All the note_p are 0, something must have gone wrong in the alloc

**Comment by Clownacy** [comment]
Like I said, that happens when `Wave.dat` doesn't load. If `InitWaveData100` returns FALSE, `org_data.InitOrgData` isn't called. `InitOrgData` calls `NoteAlloc`, which allocates the `note_p` pointers.

**Comment by GabrielRavier** [comment]
Yeah just figured out that NoteAlloc wasn't called, gonna check Wave.dat

**Comment by GabrielRavier** [comment]
StartOrganya just isn't called wtf

**Comment by Clownacy** [comment]
So AudioBackend_Init could be failing. If it's that, then either SDL_InitSubSystem or SDL_OpenAudioDevice is failing.

**Comment by GabrielRavier** [comment]
Ok so I just checked. SDL_OpenAudioDevice fails. Could you try reproducing this after going into your volume control (preferably Pulseaudio Volume Control) and setting the "Mute Audio" setting on your speakers ?

**Comment by Clownacy** [comment]
That didn't do anything. But I did realise something: [the original code checks for the DirectSound instance pointer at the start of most functions](https://github.com/Clownacy/Cave-Story-Engine-2/blob/accurate/src/Organya.cpp#L971). I figured it was pointless, since the Organya source release lacks those checks, but since the pointer is NULL if DirectSoundCreate fails (the function AudioBackend_Init replaces), then those checks would prevent that crash. I'll try adding those checks back.

**Comment by GabrielRavier** [comment]
Yeah I fixed the problem by re-enabling my speakers, but not having speakers shouldn't result in the game crashing imo

**Comment by Clownacy** [comment]
Hopefully this fixes it. It works when I test it by forcing AudioBackend_Init to fail.

**Comment by GabrielRavier** [comment]
Can confirm it works
