### ISSUE TITLE
doconfig controls arent correct with joypad

### ISSUE THREAD

**Issue by sinisterMayo** [Clownacy/Cave-Story-Engine-2#58]
when i use an xbox one controller, the controls don't line up with what i selected.

**Comment by Clownacy** [comment]
Are you using the latest release, or the latest commit? DoConfig had a bug related to button mappings corrected [back in June](https://github.com/Clownacy/Cave-Story-Engine-2/commit/729540d2b8555142e18a8b6ddf650f0525a5d009#diff-e2258c5b7064fd5be604b714f90a0830), but the last release was in May.

**Comment by sinisterMayo** [comment]
I was not aware of this. Thank you for your help.

**Comment by Clownacy** [comment]
Can you confirm this issue still happens in the newest release?

**Comment by Clownacy** [comment]
Anything?
