### ISSUE TITLE
enhanced - Extra sound formats don't support changing frequency

### ISSUE THREAD

**Issue by cuckydev** [Clownacy/Cave-Story-Engine-2#85]
Title explains it all, functions like ChangeSoundFrequency won't affect sounds that use extra sound formats

**Comment by Clownacy** [comment]
TIL ChangeSoundFrequency is actually used by something. Luckily, clownaudio recently gained support for frequency-overriding, so this should be easy to add.

**Comment by Clownacy** [comment]
[This should be fixed now.](https://github.com/Clownacy/Cave-Story-Engine-2/blob/enhanced/src/Sound.cpp#L240)
