### ISSUE TITLE
The OpenGL backend doesn't work properly

### ISSUE THREAD

**Issue by GabrielRavier** [Clownacy/Cave-Story-Engine-2#89]
Linked is a video of me trying to open the game after it was built with -DRENDERER=OpenGL3 :

[video.zip](https://github.com/Clownacy/Cave-Story-Engine-2/files/4027206/video.zip)

Though the game does work, the window stays black

**Comment by GabrielRavier** [comment]
This is what I get when I do `glxinfo | grep OpenGL` :
```
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.2.8
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 19.2.8
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 19.2.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:
``` 
so this might be the issue ?

**Comment by Clownacy** [comment]
I don't see why that would be a problem. The OpenGL renderer targets OpenGL 3.2 Core, with no extensions.

**Comment by Clownacy** [comment]
Also, just to be clear, I can't reproduce this.

**Comment by GabrielRavier** [comment]
I can reproduce this on the enhanced branch too, if you're wondering

**Comment by Clownacy** [comment]
The OpenGL backend should printf 'failed to compile shaders' if that's where it's going wrong.

**Comment by Clownacy** [comment]
And now the renderer's been updated to print shader compiler errors, instead of a generic string. Also, a new bugfix causes Cave Story to properly handle StartDirectDraw failing (which is will if OpenGL cannot initialise properly). Do any of these make a difference when you run the renderer?

**Comment by GabrielRavier** [comment]
Sadly, my normal laptop is currently broken, so I can't check if this works right now. Will check as soon as possible, which should be at best in ~1 week and at worst ~2 months

**Comment by Clownacy** [comment]
Anything yet?

**Comment by GabrielRavier** [comment]
Will check when I have the time, and reopen if it does indeed still not work

**Comment by Leo40Git** [comment]
Okay so I just tried using full-on "No SDL2" mode (OpenGL3, GLFW, miniaudio) and it works! (Apart from some weird static/hissing thing at the start of Gestation?)
