### ISSUE TITLE
Any possibility to bring the Mod Loader features into this?

### ISSUE THREAD

**Issue by Zanmato27** [Clownacy/Cave-Story-Engine-2#93]
Could it be possible to port features like the SDL input support, 3DS HUD, WASD support, alternate music, etc. into this engine?

**Comment by Clownacy** [comment]
Most of it's already there, in [the enhanced branch](https://github.com/Clownacy/Cave-Story-Engine-2/tree/enhanced): it supports extra music formats, like the alternate_music DLL, and the new keyboard/controller rebinding menu replaces the sdl_controller_input and wasd_input DLLs. Most of the graphics_enhancement DLL's features are in the enhanced branch too.

**Comment by Zanmato27** [comment]
Is there a way to map movement to D-pad? I don't see it in the configuration tool.

**Comment by Clownacy** [comment]
The newest release came out before the new controller rebinding menu was added, so you'd have to build from source.to get it. [Here's a pre-release build](https://github.com/Clownacy/Cave-Story-Engine-2/releases/tag/v2.1-enhanced-preview).

**Comment by Clownacy** [comment]
Does that close the issue, or did you want more of the Mod Loader's features adding? I'm not interested in adding Nicalis features like the 3DS HUD or drop-in support for Cave Story+'s soundtracks - CSE2E is more intended as a base for modders than a CS+ clone. Though, someone could use CSE2E as a base for one if they wanted to.
