### ISSUE TITLE
The OpenGL backend doesn't properly report failure

### ISSUE THREAD

**Issue by GabrielRavier** [Clownacy/Cave-Story-Engine-2#98]
I'm pretty sure it's because my laptop only support up to OpenGL 1.4, but trying to open the game with the OpenGL backend results in the game immediatly closing right after starting up. This is caused by `SDL_GL_CreateContext` failing. It would be nice to have some sort of error message instead of the game just not launching

**Comment by Clownacy** [comment]
This should be easy enough: since the OpenGL backend has a hard dependency on SDL2, we could use [SDL_ShowSimpleMessageBox](https://wiki.libsdl.org/SDL_ShowSimpleMessageBox).
